from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.db.database import get_db
from app.models.search import SearchJob

router = APIRouter()


@router.get("/{search_id}")
def get_report(
    search_id: str,
    db: Session = Depends(get_db),
):
    """
    Retrieve the report generated by the Report Agent for a search.
    """
    job = (
        db.query(SearchJob)
        .filter(SearchJob.id == search_id)
        .first()
    )

    if not job:
        raise HTTPException(
            status_code=404,
            detail="Search job not found.",
        )

    state = job.state or {}

    return {
        "status": job.status,
        "search_id": job.id,
        "query": job.query,
        "report": state.get("report", ""),
        "critic_result": state.get(
            "critic_result",
            "",
        ),
        "requirements": state.get(
            "requirements",
            {},
        ),
        "plan": state.get(
            "plan",
            {},
        ),
        "candidates": state.get(
            "candidates",
            [],
        ),
        "evaluations": state.get(
            "evaluations",
            [],
        ),
        "errors": state.get(
            "errors",
            [],
        ),
        "provenance": {
            "material_data": "Materials Project SOURCE_VALUE",
            "calculations": "DERIVED_VALUE",
            "interpretation": "AI_INTERPRETATION",
            "missing_properties": "UNAVAILABLE",
        },
    }


@router.post("/{search_id}/generate")
def regenerate_report(
    search_id: str,
    db: Session = Depends(get_db),
):
    """
    Return the existing workflow report.
    """
    job = (
        db.query(SearchJob)
        .filter(SearchJob.id == search_id)
        .first()
    )

    if not job:
        raise HTTPException(
            status_code=404,
            detail="Search job not found.",
        )

    state = job.state or {}

    if job.status == "running":
        raise HTTPException(
            status_code=409,
            detail="The search is still running. Wait for completion.",
        )

    return {
        "status": job.status,
        "search_id": job.id,
        "report": state.get("report", ""),
        "critic_result": state.get(
            "critic_result",
            "",
        ),
        "candidates": state.get(
            "candidates",
            [],
        ),
        "evaluations": state.get(
            "evaluations",
            [],
        ),
        "errors": state.get(
            "errors",
            [],
        ),
    }
