
from app.schemas.agent_state import SearchState
from app.services.llm import get_llm

from langchain_core.messages import HumanMessage, SystemMessage


def _extract_text(content) -> str:
    """
    Normalize Gemini/LangChain response content into plain text.
    """

    if isinstance(content, str):
        return content

    if isinstance(content, list):
        parts = []

        for item in content:
            if isinstance(item, str):
                parts.append(item)

            elif isinstance(item, dict):
                text = item.get("text")

                if text:
                    parts.append(str(text))

        return "\n".join(parts)

    return str(content)


def run(state: SearchState) -> SearchState:
    """
    Generate the final engineering report.

    Important scientific rules:
    - Materials Project values remain SOURCE_VALUE.
    - Deterministic calculations remain DERIVED_VALUE.
    - Gemini explanations are AI_INTERPRETATION.
    - Missing properties are UNAVAILABLE.
    - Never invent numerical material properties.
    - Never invent thresholds.
    - Never convert an ambiguous requirement into a fake pass/fail result.
    """

    candidates = state.get("candidates", [])
    evaluations = state.get("evaluations", [])
    requirements = state.get("requirements", {})
    critic_result = state.get("critic_result", "")
    errors = list(state.get("errors", []))

    try:
        llm = get_llm()

        prompt = f"""
You are the final report generator for MatSearch AI,
an autonomous materials discovery and engineering system.

USER REQUIREMENT
----------------
{state.get("query", "")}


PARSED REQUIREMENTS
-------------------
{requirements}


MATERIALS PROJECT CANDIDATES
----------------------------
{candidates}


DETERMINISTIC EVALUATIONS
-------------------------
{evaluations}


CRITIC RESULT
-------------
{critic_result}


YOUR TASK
---------
Generate a concise but technically rigorous engineering report based
ONLY on the supplied information.

The report should contain:

1. Requirement interpretation
2. Search methodology
3. Candidate materials
4. Candidate property evidence
5. Deterministic requirement evaluation
6. Ambiguities or unavailable properties
7. Engineering interpretation
8. Final evidence-based conclusion

IMPORTANT PROVENANCE RULES
--------------------------
Every piece of information must be treated according to its origin:

SOURCE_VALUE
-------------
A value directly retrieved from Materials Project.

DERIVED_VALUE
-------------
A value calculated deterministically by the software.

AI_INTERPRETATION
-----------------
An explanation or interpretation generated by the AI.

UNAVAILABLE
-----------
A property that was not available or could not be verified.

Do NOT present AI_INTERPRETATION as experimental or database data.

SCIENTIFIC SAFETY RULES
-----------------------
- Never invent material properties.
- Never invent numerical thresholds.
- Never estimate a missing value.
- Never claim experimental validation unless supplied.
- Never claim that a material satisfies a requirement when the
  deterministic evaluation says otherwise.
- Never change PASS, FAIL, INCOMPLETE, or AMBIGUOUS results.
- Never silently ignore unavailable data.
- Never treat qualitative phrases as numerical requirements.
- If "good thermodynamic stability" has no numerical definition,
  explicitly state that it could not be objectively verified.
- If a candidate has incomplete information, explicitly state this.
- Materials Project data is computational/database data and should
  not be described as experimental measurement.
- Clearly distinguish retrieved values from engineering interpretation.

CRITIC HANDLING
---------------
If the critic result is:

PASS:
    State that the available requirements were successfully evaluated.

PASS_WITH_AMBIGUITY:
    Explicitly identify the ambiguous requirement(s).

PASS_WITH_INCOMPLETE_DATA:
    Explicitly identify the missing properties.

REVISE:
    Explain that the current search requires another iteration.

FAIL:
    State that no validated solution was established.

Do not override the critic result.

OUTPUT STYLE
------------
Use professional materials-science engineering language.

Keep the report concise enough for a web application while still
providing useful technical information.

Do not use fake citations.

When referring to database values, identify Materials Project as
the source.

Do not fabricate references, papers, DOI numbers, experimental
results, or numerical values.
"""

        response = llm.invoke(
            [
                SystemMessage(
                    content=(
                        "You are a scientifically conservative "
                        "materials engineering report generator. "
                        "Use only supplied evidence and never "
                        "fabricate numerical properties."
                    )
                ),
                HumanMessage(content=prompt),
            ]
        )

        report = _extract_text(response.content).strip()

        if not report:
            errors.append(
                "Report Agent: Gemini returned an empty report."
            )

            return {
                **state,
                "report": "",
                "errors": errors,
                "status": "completed",
                "current_step": "report_unavailable",
            }

        return {
            **state,
            "report": report,
            "errors": errors,
            "status": "completed",
            "current_step": "generating_report",
        }

    except Exception as exc:
        errors.append(
            f"Report Agent temporarily unavailable: {str(exc)}"
        )

        return {
            **state,
            "report": "",
            "errors": errors,
            "status": "completed",
            "current_step": "report_unavailable",
        }
